version: '3.7'

services:
  db:
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./BackupSQL/Friends.sql:/docker-entrypoint-initdb.d/backup.sql
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  app:
    build:
      context: .
      dockerfile: DockerfileBackend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}

  app2:
    build:
      context: .
      dockerfile: DockerfileSendNotification
    depends_on:
      - db
      - app